apiVersion: example.argo.cisco.com/v1
kind: Resource
metadata:
  name: Agent
  group: example.argo.cisco.com
  version: v1
spec:
  spec:
    type: v1.AgentSpec
  pkey: spec.ID
  apimethods:
    - apimethod: GET
    - apimethod: PUT
    - apimethod: POST
    - apimethod: DELETE
---
kind: Struct
metadata:
  name: AgentSpec
  group: example.argo.cisco.com
  version: v1
spec:
  props:
    - prop: ID
      type: string
    - prop: CreatedAt
      type: string
    - prop: Description
      type: string
    - prop: LastUsedAt
      type: string
    - prop: Token
      type: string
---
kind: ResourceHandler
metadata:
  name: AgentHandler
spec:
  resource: example.argo.cisco.com/v1.Agent
  operations:
    - CREATE
    - UPDATE
    - DELETE
  retryStrategy:
    delay: 500
  concurrencyKey: agent
  function: golang.cisco.com/examples/example/pkg/handlers.AgentHandler
  specStatusDiscriminator: both
