apiVersion: example.argo.cisco.com/v1
kind: Resource
metadata:
  name: AgentToken
  group: example.argo.cisco.com
  version: v1
spec:
  spec:
    type: v1.AgentTokenSpec
  identity-rules:
    - identity-rule: id
      scope: org
      prop-refs:
        - prop-ref: spec.ID
          alias: agentTokenID
  apimethods:
    - apimethod: POST
      override: true
    - apimethod: DELETE
      override: true
---
kind: Struct
metadata:
  name: AgentTokenSpec
  group: example.argo.cisco.com
  version: v1
spec:
  props:
    - prop: Description
      type: string
    - prop: ID
      type: string
    - prop: CreatedAt
      type: string
    - prop: LastUsedAt
      type: string
    - prop: AgentPoolID
      type: string
---
kind: ResourceHandler
metadata:
  name: AgentTokenHandler
spec:
  resource: example.argo.cisco.com/v1.AgentToken
  operations:
    - CREATE
  retryStrategy:
    delay: 500
  concurrencyKey: AgentToken
  function: golang.cisco.com/examples/example/pkg/handlers.AgentTokenHandler
  specStatusDiscriminator: both
---
kind: Resource
metadata:
  name: AgentTokenStored
  group: example.argo.cisco.com
  version: v1
spec:
  spec:
    type: v1.AgentTokenStored
  pkey: spec.AgentTokenID
  apimethods:
    - apimethod: POST
      override: true
    - apimethod: DELETE
      override: true
---
kind: Struct
metadata:
  name: AgentTokenStored
  group: example.argo.cisco.com
  version: v1
spec:
  props:
    - prop: AgentTokenID
      type: string
    - prop: AgentToken
      type: string
---
kind: ResourceHandler
metadata:
  name: AgentTokenStoredHandler
spec:
  resource: example.argo.cisco.com/v1.AgentTokenStored
  operations:
    - CREATE
  retryStrategy:
    delay: 500
  concurrencyKey: AgentTokenStored
  function: golang.cisco.com/examples/example/pkg/handlers.AgentTokenStoredHandler
  specStatusDiscriminator: both