apiVersion: example.argo.cisco.com/v1
kind: Resource
metadata:
  name: Agent
  group: example.argo.cisco.com
  version: v1
spec:
  spec:
    type: v1.AgentSpec
  pkey: spec.description
  apimethods:
    - apimethod: GET
    - apimethod: POST
    - apimethod: DELETE
---
kind: Struct
metadata:
  name: AgentSpec
  group: example.argo.cisco.com
  version: v1
spec:
  props:
    - prop: description
      type: string
    - prop: id
      type: string
    - prop: agentpool
      type: string
    - prop: agentpoolId
      type: string
    - prop: organization
      type: string
    - prop: name
      type: string
    - prop: token
      type: string
      userAccess: invisible
---
kind: ResourceHandler
metadata:
  name: AgentHandler
spec:
  resource: example.argo.cisco.com/v1.Agent
  operations:
    - CREATE
    - DELETE
  retryStrategy:
    delay: 500
  concurrencyKey: Agent
  function: golang.cisco.com/examples/example/pkg/handlers.AgentHandler
  specStatusDiscriminator: both
---
kind: ValidationHandler
metadata:
  name: AgentValidator
spec:
  resource: example.argo.cisco.com/v1.Agent
  operations:
    - CREATE
    - UPDATE
    - DELETE
  function: golang.cisco.com/examples/example/pkg/handlers.AgentValidator
---
kind: Resource
metadata:
  name: TokenList
  plural: tokenList
  group: example.argo.cisco.com
  version: v1
spec:
  spec:
    type: v1.TokenListSpec
  pkey: spec.agentpool
  apimethods:
    - apimethod: GET
      override: true
---
kind: Struct
metadata:
  name: TokenListSpec
  group: example.argo.cisco.com
  version: v1
spec:
  props:
    - prop: agentpool
      type: string
    - prop: tokens
      type: []string