apiVersion: example.argo.cisco.com/v1
kind: Resource
metadata:
  name: AgentPool
  group: example.argo.cisco.com
  version: v1
spec:
  spec:
    type: v1.AgentPoolSpec
  identity-rules:
    - identity-rule: orgAgentPl
      scope: org
      prop-refs:
        - prop-ref: spec.Organization
          alias: organizations
        - prop-ref: spec.Name
          alias: agentname
    - identity-rule: id
      scope: org
      prop-refs:
        - prop-ref: spec.ID
          alias: agentid
  apimethods:
    - apimethod: GET
      override: true
    - apimethod: POST
      override: true
    - apimethod: DELETE
      override: true
---
kind: Struct
metadata:
  name: AgentPoolSpec
  group: example.argo.cisco.com
  version: v1
spec:
  props:
    - prop: Name
      type: string
    - prop: ID
      type: string
    - prop: Organization
      type: string
---
kind: ResourceHandler
metadata:
  name: AgentPoolHandler
spec:
  resource: example.argo.cisco.com/v1.AgentPool
  operations:
    - CREATE
  retryStrategy:
    delay: 500
  concurrencyKey: AgentPool
  function: golang.cisco.com/examples/example/pkg/handlers.AgentPoolHandler
  specStatusDiscriminator: both
---
kind: Resource
metadata:
  name: OrgAgentPl
  group: example.argo.cisco.com
  version: v1
spec:
  spec:
    type: v1.OrgAgentPlSpec
  pkey: spec.Organization
  apimethods:
    - apimethod: GET
      override: true
---
kind: Struct
metadata:
  name: OrgAgentPlSpec
  group: example.argo.cisco.com
  version: v1
spec:
  props:
    - prop: Organization
      type: string
    - prop: AgentPools
      type: []v1.AgentPlSpec
---
kind: Struct
metadata:
  name: AgentPlSpec
  group: example.argo.cisco.com
  version: v1
spec:
  props:
    - prop: Name
      type: string
    - prop: ID
      type: string